apiVersion: apps/v1
kind: Deployment
metadata:
  #creationTimestamp: null
  labels:
    app: banyantree
  name: banyantree
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banyantreeapi
  strategy: {}
  template:
    metadata:
      #creationTimestamp: null
      labels:
        app: banyantreeapi
    spec:
      containers:
      - image: banyantree
        name: banyantree
        imagePullPolicy: Never
        resources: {}
        ports:
          - containerPort: 80
status: {}
